dist: trusty
sudo: false
language: python
python:
  - "3.6"
before_install:
  - python --version
install:
  - pip install cython
  - pip install tox
before_script:
  - pip install grpcio-tools
  - make cython protos
script:
  - travis_wait 60 tox
